### PR TITLE
repo structure: rename src/ directory to microdns/

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
With that change, libmicrodns can be used as a meson subproject
without requiring the parent project to use a different include
path.

This also makes the examples more readily copypastable, as the
include is switched from `#include "microdns.h"` to
`#include <microdns/microdns.h`, which is how external compilation
units are expected to perform the inclusion.

In addition, this also removes the unneeded compat.h inclusion from
the announce example, this has been tested and is known to compile
on Windows with mingw / MSYS2.

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
This is a follow-up to my meson port ( #24 ) . I hope this is acceptable, subprojects are a very nice meson feature :)

**Comment by ePirat** [comment]
IMO it would be better to split the headers out into a `include/microdns` directory for the public headers.

**Comment by MathieuDuponchelle** [comment]
wfm too, but that's more of a departure from the current layout, and I personally prefer having the headers in the same folder as the C files, really a matter of personal taste though

**Comment by MathieuDuponchelle** [comment]
ping?

**Comment by chouquette** [comment]
I agree with @ePirat , I'm more in favor of keeping the sources in `src/`, but see no problem with having the headers in `include/` or `microdns/`

**Comment by MathieuDuponchelle** [comment]
then `include/microdns` that is, if we keep the sources in `src` I think the least surprising layout is to have an `include` directory next to it :)

**Comment by chouquette** [comment]
That's fine by me :)

**Comment by MathieuDuponchelle** [comment]
done @chouquette :)

**Comment by jbkempf** [comment]
LGTM now.

**Comment by MathieuDuponchelle** [comment]
Thanks guys

**Pull request merged**
