### PR TITLE
Fix build on Windows

### PR DESCRIPTION
**Pull request by tp-m**
Need to export the new symbols:
```
tests_unittests.c.obj : error LNK2019: unresolved external symbol mdns_parse referenced in function simple_answer_test
tests_unittests.c.obj : error LNK2019: unresolved external symbol mdns_free referenced in function simple_answer_test
subprojects/libmicrodns/unittest.exe : fatal error LNK1120: 2 unresolved externals
```

Also remove old .def and .version files that are no longer used.

Would be great if we could get a new tag/release with this fix.

### CODE REVIEW

**Comment by chouquette** [comment]
Hi,

Thanks for the super quick fix! I'm perfectly fine with removing the .def files, however I have mixed feelings about exposing some functions which are only used for testing purposes.

I wonder if we shouldn't enforce static linking when building the test programs, but I'm not sure how to do that with meson.

I'll investigate

**Comment by tp-m** [comment]
Right. I can see why you have mixed feelings, but arguably no one would be able to use these functions anyway because they're not in the publicly installed header files, and I don't think it's unusual to have such 'private exported symbols' in libraries.

If you do static linking for tests you'd have to build the lib twice on Windows (not that it matters much since it's tiny).

**Comment by robUx4** [comment]
It doesn't look like a regression not to run tests with the DLL version on Windows. The functions are not present in the `libmicrodns.def`. So that might put in another Pull Request to add this feature alone (which is tricky).

**Comment by tp-m** [comment]
> The functions are not present in the `libmicrodns.def`. So that might put in another Pull Request to add this feature alone (which is tricky).

Sorry, not sure what you are saying here :) What is "this feature" in the above sentence and why is it tricky?

**Comment by robUx4** [comment]
The sentence missed a word:
> So that might be put in another Pull Request to add this feature alone (which is tricky).

The feature is supporting unittests with a DLL version of libmicrodns. It's currently not supported, as evidenced by the missing entries in the .def file. It's unrelated to the primary goal of this PR to fix the Windows build, or the title is wrong.

**Comment by tp-m** [comment]
The `.def` file is no longer used anywhere, the removal of that is just a clean-up.

**Comment by tp-m** [comment]
I can remove the commit that removes the `.def` and `.version` files, the only relationship to the PR title is that it's confusing to have them around because one would think the exports in the `.def` files matter but they don't because it's unused :)

**Comment by chouquette** [comment]
If you could put the removal of the .def files in a separate MR that would be great! 

Regarding the build fix, I think I can work something out with `extract_objects`

**Comment by tp-m** [comment]
> If you could put the removal of the .def files in a separate MR that would be great!

Done.

Let me know if you need me to do or test anything, thanks!

**Comment by tp-m** [comment]
I guess this should be closed in favour of #31.

**Comment by chouquette** [comment]
Closed in favor of #31, thanks a lot for reporting and helping throughout the fixes :)

**Pull request closed without merging**
