### PR TITLE
refactor to support announcing mdns records as well as resolving them

### PR DESCRIPTION
**Pull request by sleepybishop**
thank you for this library, it is really helpful and i really appreciate the small footprint.

i needed the ability to also announce mdns packets as well so ive made the following changes.
i offer the following for merge consideration in case its useful to others with similar use case.

up to 8b74eb7 the api should be backwards compatible.

the last few commits break the previous api but reduce the code size by generalizing common logic.

### CODE REVIEW

**Comment by jbkempf** [comment]
Wow, this is really cool!

I'll need a bit of time to review, but this is a great idea.

**Comment by jbkempf** [comment]
Hello,
Thanks a lot for this request.

Remarks:
- please fix your name in your git configuration ("joe" is too short)
- commit 1 and 2 should be merged 
- So far, WE DO NOT CARE about API compatibility, AT ALL. Break it, without problems!
- Simplifications of API are very welcome!
- why "replace strtok() with strcspn()" ?
- why renaming callback to cb?
- fix compiler warning should be merged with previous commits,
- update exports should be done at the same time as the functions are added
- readd line commit should also be merged with previous commits.

For the last 3 commits, 'git rebase -i origin/master' is a blessing!

**Comment by sleepybishop** [comment]
hello, thanks for the feedback, i'll make the necessary updates.

with regard to your questions:
- strtok() modifies it's argument, so using a const char buffer in the rr's or calling mdns_print after rr_write() wouldn't be possible.
- i can undo the renames, i was trying to save space on my screen, it's unlikely of any benefit to many others.

**Comment by jbkempf** [comment]
Excellent!
Merged!

**Comment by jbkempf** [comment]
Btw, you might not have seen, but announce does not build on Windows because of inet_pton.

**Comment by sleepybishop** [comment]
windows vista and higher have inetPton() and inetNtop(), a thin shim in compat.h might help address the issue if supporting XP and lower is not a concern.

**Comment by jbkempf** [comment]
I made a fix for that, already :)

**Pull request closed without merging**
