### PR TITLE
Simplify generation of pkgconfig file

### PR DESCRIPTION
**Pull request by hadess**
Use meson's pkgconfig module to generate the pkg-config file, rather
than using old-school autotools patterns.

(The `-lws2_32 -liphlpapi` link should get automatically added for Windows systems, but I don't have a way to test this)

### CODE REVIEW

**Comment by jbkempf** [comment]
It LGTM, but we need to check on Windows, because I don't see what would bring the phlpapi magically

**Comment by hadess** [comment]
> It LGTM, but we need to check on Windows, because I don't see what would bring the phlpapi magically

The `deps` line 67 of the meson.build. Both libraries are listed in the deps, so we shouldn't need to list them manually.

**Comment by jbkempf** [comment]
> > It LGTM, but we need to check on Windows, because I don't see what would bring the phlpapi magically
> 
> The `deps` line 67 of the meson.build. Both libraries are listed in the deps, so we shouldn't need to list them manually.

I’m an idiot. Ill test this.

**Comment by xclaesse** [comment]
@hadess FYI, made a small simplification of your PR there: https://github.com/videolabs/libmicrodns/pull/49.

**Pull request merged**
