### PR TITLE
Meson: Use pkgconfig generator

### PR DESCRIPTION
**Pull request by xclaesse**
It's cleaner and also more correct because `@LIBSOCKET@` should be in `Libs.private` AFAIK. Meson does that correctly.

### CODE REVIEW

**Comment by jbkempf** [comment]
See #45

**Comment by xclaesse** [comment]
@jbkempf Not sure to understand why this PR is marked merged, seems it's #45 that got merged instead?

I think my PR is more correct:
- pkg_cdata is unused and should have been deleted completely
- `libmicrodns` should be passed as first positional argument and not in `libraries:` keyword argument.
- `deps` should not be specified as public requires, they are private dependencies and Meson will add them automatically, no need to mention them.

**Comment by jbkempf** [comment]
> @jbkempf Not sure to understand why this PR is marked merged, seems it's #45 that got merged instead?

Some git/github issue.

#45 was first, and it's 90% of the work, so it's polite to merge the first MR. Feel free to send a patch to improve it.

**Comment by xclaesse** [comment]
Ok, opened new PR: https://github.com/videolabs/libmicrodns/pull/49

**Comment by jbkempf** [comment]
> Ok, opened new PR: #49

Thanks. Merged.

**Pull request merged**
