### PR TITLE
Meson: Simplify pkgconfig generator

### PR DESCRIPTION
**Pull request by xclaesse**
- pkg_cdata is unused and should have been deleted completely
- libmicrodns should be passed as first positional argument and not in
  libraries: keyword argument.
- deps should not be specified as public requires, they are private
  dependencies and Meson will add them automatically, no need to mention
  them.

### CODE REVIEW

**Comment by jbkempf** [comment]
LGTM, but why do you remove the version part?

**Comment by xclaesse** [comment]
> LGTM, but why do you remove the version part?

Meson takes project version by default.

**Comment by jbkempf** [comment]
> > LGTM, but why do you remove the version part?
> 
> Meson takes project version by default.

ok

**Comment by xclaesse** [comment]
FYI, with this PR on Windows the pc file contains:
```
prefix=c:/
includedir=${prefix}/include
libdir=${prefix}/lib

Name: microDNS
Description: mDNS simple implementation
Version: 0.2.0
Libs: -L${libdir} -lmicrodns
Libs.private: -lws2_32 -liphlpapi
Cflags: -I${includedir}
```

**Comment by jbkempf** [comment]
It seems similar to the previous version, except it had `exec_prefix` but I don't see the need...

**Pull request merged**
